name: Render Rmd and update Pages HTML

on:
  push:
    branches: [ main ]
    paths:
      - '**.Rmd'
      - '.github/workflows/render.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # get full history so rebase works

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system requirements & R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rmarkdown
            any::sf
            any::sp
            any::spdep
            any::ggplot2
            any::gstat

      - name: Knit variogram_tutorial1.rmd to index.html
        run: |
          Rscript -e "rmarkdown::render('variogram_tutorial1.rmd', output_format='html_document', output_file='index.html')"

      - name: Commit HTML (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "CI: render index.html" || echo "No changes to commit"

      - name: Rebase onto latest main and push
        run: |
          git fetch origin
          git rebase origin/main || { echo "Rebase failed, aborting & falling back to merge"; git rebase --abort; git pull --no-rebase --no-edit origin main; }
          git push origin HEAD:main
